--- 
- 
  gather_facts: false
  hosts: windows
  name: "Windows Update"
  tasks: 
    - 
      name: "Running Windows Update"
      register: result
      win_updates: 
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
    - 
      debug: var=result
    - 
      when: result.reboot_required
      win_reboot: ~
